// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKJlvWN6U2ScSOKVaaYrX86Th-xP-WKs',
    appId: '1:65333563976:web:091c2fb341efbfdf673e7d',
    messagingSenderId: '65333563976',
    projectId: 'cost-management-be09d',
    authDomain: 'cost-management-be09d.firebaseapp.com',
    storageBucket: 'cost-management-be09d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCguOoeh4MnPPf3kyZDRkoqXu3Sb2y34nw',
    appId: '1:65333563976:android:0051dfbbb50684cc673e7d',
    messagingSenderId: '65333563976',
    projectId: 'cost-management-be09d',
    storageBucket: 'cost-management-be09d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDPrnMdasEjJRWyo1-cAWVScocXD4KRY',
    appId: '1:65333563976:ios:1f32c965b901a1ad673e7d',
    messagingSenderId: '65333563976',
    projectId: 'cost-management-be09d',
    storageBucket: 'cost-management-be09d.firebasestorage.app',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDPrnMdasEjJRWyo1-cAWVScocXD4KRY',
    appId: '1:65333563976:ios:1f32c965b901a1ad673e7d',
    messagingSenderId: '65333563976',
    projectId: 'cost-management-be09d',
    storageBucket: 'cost-management-be09d.firebasestorage.app',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaKJlvWN6U2ScSOKVaaYrX86Th-xP-WKs',
    appId: '1:65333563976:web:1a2b503de82f60ee673e7d',
    messagingSenderId: '65333563976',
    projectId: 'cost-management-be09d',
    authDomain: 'cost-management-be09d.firebaseapp.com',
    storageBucket: 'cost-management-be09d.firebasestorage.app',
  );
}
